Models/Simp.cs
namespace CrudContactListMvc.Models
{
    public class Simp
    {
        public int Id { get; set; }
        public List<Subcategory> SubcategoryList { get; set; }
        public List<Category> CategoryList { get; set; }
        public List<Contact> ContactList { get; set; }

        public Simp()
        {
            
        }
    }
}

Controllers/SimpsController.cs
using CrudContactListMvc.Data;
using CrudContactListMvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CrudContactListMvc.Controllers
{
    public class SimpsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SimpsController(ApplicationDbContext context)
        {
            _context = context;
        }



        // GET: MAIN PAGE
        public IActionResult Index()
        {
            return View();
        }



        // ===================================
        // BLOCK FOR INTERACTIONS WITH CONTACT
        // ===================================

        // GET: Contacts
        public async Task<IActionResult> Contact_Index(IFormCollection form)
        {
            var applicationDbContext = _context.Contact.Include(c => c.Category).Include(c => c.Subcategory);
            return PartialView(await applicationDbContext.ToListAsync());
        }

        // GET: Contacts/ShowSearchForm
        public async Task<IActionResult> Contact_Search(IFormCollection form)
        {
            return PartialView();
        }

        // PoST: Contacts/ShowSearchResults
        public async Task<IActionResult> Contact_SearchShowResults(String SearchPhrase)
        {
            return PartialView("Contact_Index", await _context.Contact.Where(j => (j.Name.Contains(SearchPhrase) ||
                                                                     j.Surname.Contains(SearchPhrase) ||
                                                                     j.Email.Contains(SearchPhrase) ||
                                                                     //j.BirthDate.Date.Equals(DateTime.Parse(SearchPhrase).Date) ||
                                                                     j.Phone.Contains(SearchPhrase))).ToListAsync());
        }

        // GET: Contacts/Details/5
        [Authorize]
        public async Task<IActionResult> Contact_Details(IFormCollection form)
        {
            string? id_str = form["button"];
            if (id_str == null)
            {
                return NotFound();
            }
            int id = int.Parse(id_str);

            var contact = await _context.Contact
                .Include(c => c.Category)
                .Include(c => c.Subcategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return PartialView(contact);
        }

        // GET: Contacts/Create
        [Authorize]
        public IActionResult Contact_Create(IFormCollection form)
        {
            // string for condition to show drop-down subcategory menu
            Category expectedCategory = _context.Category.Where(m => m.Id == 1).First();
            ViewBag.DropDownCategory = expectedCategory.Name;
            //ViewBag.DropDownCategory = "Business";


            // other category - it is used to show text field instead of drop-down
            Category otherCategoryName = _context.Category.Where(m => m.Id == 3).First();
            ViewBag.otherCategoryName = otherCategoryName.Name;
            //ViewBag.otherCategoryName = "Other";


            // Send emails to View. This are emails from the Database
            // Reason: They must be UNIQUE
            List<string> emails = _context.Contact.Select(m => m.Email).ToList();
            ViewBag.emails = emails;




            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Name");



            // Working, but pointless - it should be done in Views JavaScript

            /*
            var subcategories = _context.Category.ToList();
            // Create a list of SelectListItem
            var subcategoryList = subcategories.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            // Add a new option
            subcategoryList.Insert(0, new SelectListItem { Value = "", Text = "" });
            // Pass the list to the SelectList constructor
            ViewData["SubcategoryId"] = new SelectList(subcategoryList, "Value", "Text");
            */




            // Doesn't working

            //SelectList slSubcategory = new SelectList(_context.Subcategory, "Id", "Name");
            //slSubcategory.Insert(0, new SelectListItem { Value = "", Text = "" });
            //ViewData["SubcategoryId"] = slSubcategory;



            // NULL values in Selection List should be implemented in Views JavaScript
            ViewData["SubcategoryId"] = new SelectList(_context.Subcategory.Where(m => m.CategoryId == 1), "Id", "Name");


            return PartialView();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Contact_CreateAddRecord(IFormCollection form)
        {
            string newSubcatName = form["NewCategory"];

            Contact contact = new Contact
            {
                //Id = int.Parse(form["Id"]),
                Email = form["Email"],
                Name = form["Name"],
                Surname = form["Surname"],
                Password = form["Password"],
                Phone = form["Phone"],
                BirthDate = DateTime.Parse(form["BirthDate"]),
                CategoryId = int.Parse(form["CategoryId"])
            };

            // SubcategoryId can be in at least 3 different states
            if (contact.CategoryId == 3)
            {
                int catId = 3;
                Subcategory newSub = new Subcategory
                {
                    Name = newSubcatName,
                    CategoryId = catId
                };
                _context.Add(newSub);
                await _context.SaveChangesAsync();

                contact.SubcategoryId = newSub.Id;
                //contact.SubcategoryId = _context.Subcategory.Where(m => m.Name == newSubcatName).Last().Id;
            }
            else if (contact.CategoryId == 2)
            {
                contact.SubcategoryId = null;
            }
            else
            {
                contact.SubcategoryId = int.Parse(form["SubcategoryId"]);
            }




            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Name", contact.CategoryId);
            ViewData["SubcategoryId"] = new SelectList(_context.Subcategory, "Id", "Name", contact.SubcategoryId);
            return PartialView(contact);
        }

        // GET: Contacts/Edit/5
        [Authorize]
        public async Task<IActionResult> Contact_Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Id", contact.CategoryId);
            ViewData["SubcategoryId"] = new SelectList(_context.Subcategory, "Id", "Id", contact.SubcategoryId);
            return PartialView(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Contact_EditApply(int id, [Bind("Id,Email,Name,Surname,Password,Phone,BirthDate,CategoryId,SubcategoryId")] Contact contact)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Contact_ContactExists(contact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Id", contact.CategoryId);
            ViewData["SubcategoryId"] = new SelectList(_context.Subcategory, "Id", "Id", contact.SubcategoryId);
            return PartialView(contact);
        }

        // GET: Contacts/Delete/5
        [Authorize]
        public async Task<IActionResult> Contact_Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .Include(c => c.Category)
                .Include(c => c.Subcategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return PartialView(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Contact_DeleteConfirmed(int id)
        {
            var contact = await _context.Contact.FindAsync(id);
            if (contact != null)

Views/Simps/Category_Delete.cshtml
@model CrudContactListMvc.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h1>Delete</h1>
<p>Current time: @DateTime.Now</p>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</div>

Views/Simps/Category_Details.cshtml
@model CrudContactListMvc.Models.Category

@{
    ViewData["Title"] = "Details";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h1>Details</h1>

<div>
    <h4>Category</h4>
    <p>Current time: @DateTime.Now</p>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subcategory)
        </dt>

        @{
            if (Model.Subcategory != null)
            {
                <dd></dd>
                foreach (Subcategory item in Model.Subcategory)
                {
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => item.Name)
                    </dd>
                }
            }
        }

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</div>

Views/Simps/Category_Edit.cshtml
@model CrudContactListMvc.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h1>Edit</h1>

<h4>Category</h4>
<p>Current time: @DateTime.Now</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>


<script>
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
</script>

Views/Simps/Category_Index.cshtml
@model IEnumerable<CrudContactListMvc.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h1>Categories</h1>
<p>Current time: @DateTime.Now</p>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Views/Simps/Contact_Create.cshtml
@model CrudContactListMvc.Models.Contact

@{
    ViewData["Title"] = "Create";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h1>Create</h1>

<h4>Contact</h4>
<p>Current time: @DateTime.Now</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" onchange="CheckEmail()" id="emailInput"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId" onchange="Select()"></select>
            </div>
            <div class="form-group" id="hiddenSubcategory">
                <label asp-for="Subcategory" class="control-label"></label>
                <select asp-for="SubcategoryId" class="form-control" asp-items="ViewBag.SubcategoryId"></select>
            </div>
            <div class="form-group" id="NewCategoryDiv" style="display: none;">
                <label class="control-label">New subcategory</label>
                <input id="NewCategory" name="NewCategory" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>

<!-- https://stackoverflow.com/questions/74607305/how-do-you-hide-a-div-element-based-on-user-input-on-a-razor-page -->

<script>
    function Select()
    {
        //get the element by id
        var select = document.getElementById("CategoryId");
        var selectSubcat = document.getElementById("SubcategoryId");
        //get the option's text
        var index = select.selectedIndex;
        var text = select.options[index].text;
        // Business has id 1 in the database
        // get from controller through 
        var categoryName = "@ViewBag.DropDownCategory";
        //if option's text is not Business, hide the second dropdownlist.
        // if (text != "Business") {
        if (text != categoryName) {
            //hiden the dropdownlist
            document.getElementById("hiddenSubcategory").style.display = 'none';

            // Setting null value at SelectList
            var nullVal = "";
            var findedNullOption = selectSubcat.querySelector(`option[value="${nullVal}"]`);
            if (findedNullOption == null)
            {
                var newOption = new Option('', '');
                selectSubcat.add(newOption);
                selectSubcat.value = '';
            }

        } else {
            //show the dropdownlist
            document.getElementById("hiddenSubcategory").style.display = 'block';


            // Log all option values
            // var selectSubcat = document.getElementById("SubcategoryId");
            // console.log('Current options:');
            // for (let option of selectSubcat.options) {
            //     console.log(option.value);
            // }


            // Removing null value at SelectList
            var valueToRemove = "";
            var optionToRemove = selectSubcat.querySelector(`option[value="${valueToRemove}"]`);
            if (optionToRemove)
            {
                optionToRemove.remove();
            }
            // Set the first remaining element as the active value
            if (selectSubcat.options.length > 0)
            {
                selectSubcat.selectedIndex = 0;
            }


        }


        var otherCategoryName = "@ViewBag.otherCategoryName";
        if (text == otherCategoryName) {
            document.getElementById("NewCategoryDiv").style.display = 'block';
        }
        else {
            document.getElementById("NewCategoryDiv").style.display = 'none';
        }

    }


    function CheckEmail()
    {
        var emailInput = document.getElementById("emailInput");
        var emails = @Html.Raw(Json.Serialize(ViewBag.emails));
        if (emails.includes(emailInput.value))
        {
            emailInput.value = "This email is already in the Database."
        }

    }



</script>


<!-- DEfault View block element -->
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

Views/Simps/Contact_Index.cshtml
@model IEnumerable<CrudContactListMvc.Models.Contact>

@{
    ViewData["Title"] = "Index";
}

<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }

    .buttons_inline > form {
        display: inline;
    }
</style>

<div class="all_center">
<h1>Contacts</h1>
<p>Current time: @DateTime.Now</p>

<p>
    <form id="Partial_Contact_form_getCreate" asp-action="Contact_Create" asp-controller="Simps">
        <button id="Partial_Contact_getCreate"
                name="Partial_Contact_getCreate"
                type="submit"
                value="Partial_Contact_getCreate">
            Create New
        </button>
    </form>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subcategory)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subcategory.Name)
            </td>
            <td>
                <div class="buttons_inline">

                    <form id="Partial_Contact_form_getEdit"
                          asp-action="Contact_Edit"
                          asp-controller="Simps">
                        <button id="Partial_Contact_getEdit"
                                name="Partial_Contact_getEdit"
                                type="submit"
                                value="@item.Id">
                            Edit
                        </button>
                    </form> | 

                    <form id="Partial_Contact_form_getDetails"
                          asp-action="Contact_Details"
                          asp-controller="Simps">
                        <button id="Partial_Contact_getDetails"
                                name="button"
                                type="submit"
                                value="@item.Id">
                            Details
                        </button>
                    </form> | 

                    <form id="Partial_Contact_form_getDelete"
                          asp-action="Contact_Delete"
                          asp-controller="Simps">
                        <button id="Partial_Contact_getDelete"
                                name="Partial_Contact_getDelete"
                                type="submit"
                                value="@item.Id">
                            Delete
                        </button>
                    </form>

                </div>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>

<script src="js/site.js"></script>

Views/Simps/Contact_Search.cshtml
<style>
    .all_center * {
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>

<div class="all_center">
<h4>Search contact</h4>
<p>Current time: @DateTime.Now</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Contact_ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Simps/Index.cshtml
@model IEnumerable<CrudContactListMvc.Models.Simp>

<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet">
</head>

<style>
	.space-grotesk-regular {
		font-family: "Space Grotesk", sans-serif;
		font-optical-sizing: auto;
		font-weight: 400;
		font-style: normal;
	}

	* {
		font-family: space-grotesk-regular;
	}

	.list {
		display: grid;
		grid-template-columns: repeat(2, auto);
		grid-template-rows: repeat(2, 1fr);
		grid-column-gap: 10px;
		grid-row-gap: 10px;
		place-content: center;
	}

	.spa-class-box {
		background-color: #D6D9CC;
		margin-top: 30px;
		margin-bottom: 30px;
		border: solid #0D0D0D 2px;
		border-radius: 25px;
		width: 450px;
		text-align: center;
		margin-left: auto;
		margin-right: auto;
		height: 200px;
	}
	
	.spa-view-button {
		padding: 20px;
		background-color: #6F7356;
	}
	
	.spa-view-button button {
		background-color: #BF3604;
	}
	
	.spa-view-content {
		background-color: #D99982;
		height: 50px;
		text-align: center;
		margin-left: auto;
		margin-right: auto;
	}


	

	.spa-class-box-x2 {
		width: 910px!important;
		/* height: 1000px; */
	}

	.spa-view-content-x2 {
		height: 50px!important;
	}

	.spa-view-content-x2 + .spa-view-content-x2 {
		height: 0px!important;
	}

	/* .spa-view-content-x2 {
		height: 800px;
	} */

</style>

<body>
	<h1>Single Page Application</h1>
	<p>Current time: @DateTime.Now</p>

	<!-- Multi-block -->
	<div class="spa-class-box spa-class-box-x2">
		<h2>Multi-Block, all-in-one</h2>
		<div class="spa-view-button">
			<form id="Contact_Multiblock_form_getIndex" asp-action="Contact_Index" asp-controller="Simps">
				<button id="Contact_Multiblock_getIndex"
						name="Contact_Multiblock_getIndex"
						type="submit"
						value="Contact_Multiblock_getIndex">
					Get Contact Index
				</button>
			</form>
		</div>
		<div class="spa-view-content spa-view-content-x2" id="Contact_Multiblock_getIndex_content">
			<p>After button click, here will be loaded content.</p>
		</div>
	</div>

	<!-- ==================== -->
	<!-- CONTACT INTERACTIONS -->
	<!-- 1 wide block -->
	<!-- Grid 2x2 -->
	<!-- 1 wide block -->
	<!-- ==================== -->

	<!-- Block 1 -->
	<div class="spa-class-box spa-class-box-x2">
		<h2>Contacts Index</h2>
		<div class="spa-view-button">
			<form id="Contact_form_getIndex" asp-action="Contact_Index" asp-controller="Simps">
				<button id="Contact_getIndex"
						name="Contact_getIndex"
						type="submit"
						value="Contact_getIndex">
					Get Contact Index
				</button>
			</form>
		</div>
		<div class="spa-view-content spa-view-content-x2" id="Contact_getIndex_content">
			<p>After button click, here will be loaded content.</p>
		</div>
	</div>

	<div class="list">

		<!-- Block 2 -->
		<div class="spa-class-box">
			<h2>Contacts Create</h2>
			<div class="spa-view-button">
				<form id="Contact_form_getCreate" asp-action="Contact_Create" asp-controller="Simps">
					<button id="Contact_getCreate"
							name="Contact_getCreate"
							type="submit"
							value="Contact_getCreate">
						Get Contact Create
					</button>
				</form>
			</div>
			<div class="spa-view-content" id="Contact_getCreate_content">
				<p>After button click, here will be loaded content.</p>
			</div>
		</div>

		<!-- Block 3 -->
		<div class="spa-class-box">
			<h2>Contacts Details</h2>
			<div class="spa-view-button" style="height: 70px;">
				<!--
				<form id="Contact_form_getDetails" asp-action="Contact_Details" asp-controller="Simps">
					<button id="Contact_getDetails"
							name="Contact_getDetails"
							type="submit"
							value="Contact_getDetails">
						Get Contact Details
					</button>
				</form>
				-->
			</div>
			<div class="spa-view-content" id="Contact_getDetails_content">
				<p>After button click, here will be loaded content.</p>
			</div>
		</div>

		<!-- Block 4 -->
		<div class="spa-class-box">
			<h2>Contacts Edit</h2>
			<div class="spa-view-button">
				<!--
				<form id="Contact_form_getEdit" asp-action="Contact_Edit" asp-controller="Simps">
					<button id="Contact_getEdit"
							name="Contact_getEdit"
							type="submit"
							value="Contact_getEdit">
						Get Contact Edit
					</button>
				</form>
				-->
			</div>
			<div class="spa-view-content" id="Contact_getEdit_content">
				<p>After button click, here will be loaded content.</p>
			</div>
		</div>

		<!-- Block 5 -->
		<div class="spa-class-box">
			<h2>Contacts Delete</h2>
			<div class="spa-view-button">
				<!--
				<form id="Contact_form_getDelete" asp-action="Contact_Delete" asp-controller="Simps">
					<button id="Contact_getDelete"
							name="Contact_getDelete"
							type="submit"
							value="Contact_getDelete">
						Get Contact Delete
					</button>
				</form>
				-->
			</div>
			<div class="spa-view-content" id="Contact_getDelete_content">
				<p>After button click, here will be loaded content.</p>
			</div>
		</div>

	</div>

	<!-- Double width block - search -->
	<!-- Block 6 -->
	<div class="spa-class-box spa-class-box-x2">
		<h2>Contacts Search</h2>
		<div class="spa-view-button">
			<form id="Contact_form_getSearch" asp-action="Contact_Search" asp-controller="Simps">
				<button id="Contact_getSearch"
						name="Contact_getSearch"
						type="submit"
						value="Contact_getSearch">
					Get Contact Search
				</button>
			</form>
		</div>
		<div class="spa-view-content spa-view-content-x2" id="Contact_getSearch_content">
			<p>After button click, here will be loaded content.</p>
		</div>
		<div class="spa-view-content spa-view-content-x2" id="Contact_getSearchResults_content">
			<p>Space for search results</p>
		</div>
	</div>



































	<!--

	<div class="spa-class-box">
		<h2>Contacts</h2>
		<div class="spa-view-button">
			<button>Get Contact Index</button>
		</div>
		<div class="spa-view-content">
			<p>After button click, here will be loaded content.</p>
		</div>
	</div>

	-->


</body>



<!-- Java Script -->
<!-- Java Script in wwwroot/js/site.js -->
<!--
<script>
	
</script>
-->